version: 3.9

services:
  web:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - webnet

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      -user_service
      -auth_service
    networks:
      - webnet
  
  user_service:
    build: ./User_service
    ports:
      - "3001:3001"
    networks:
      - webnet
  
  auth_service:
    build: ./Auth_service
    ports:
      - "3002:3002"
    networks:
      - webnet

  chat_service:
    build: ./Chat_service
    ports:
      - "3003:3003"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge