services:
  web:
    build: ./FRONTEND
    ports:
      - "8443:8443"
    networks:
      - webnet

  gateway:
    build: ./BACKEND/Gateway
    ports:
      - "3000:3000"
    depends_on:
      - userservice
      - authservice
    networks:
      - webnet
  
  userservice:
    build: ./BACKEND/User
    ports:
      - "3001:3001"
    networks:
      - webnet
  
  authservice:
    build: ./BACKEND/Authentication
    ports:
      - "3002:3002"
    env_file:
      - ./BACKEND/Authentication/.env
    networks:
      - webnet

  chatservice:
    build: ./BACKEND/Chat
    ports:
      - "3004:3004"
    networks:
      - webnet

  onlinepongservice:
    build: ./BACKEND/OnlinePong
    ports:
      - "3005:3005"
    networks:
      - webnet

  friendservice:
    build: ./BACKEND/Friend
    ports:
      - "3006:3006"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge