services:
  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault/data
      - ./vault/config.hcl:/vault/config/config.hcl
      - ./vault/config:/vault/config/
    environment:
      VAULT_ADDR: https://0.0.0.0:8200
    command: vault server -config=/vault/config/config.hcl
    
  web:
    build: ./FRONTEND
    container_name: web
    ports:
      - "8080:8080"
    networks:
      - webnet

  wafnginx:
    build: ./FRONTEND/WAF
    container_name: wafnginx
    ports:
      - "9443:9443"
    depends_on:
      - web
      - gateway
    networks:
      - webnet

  gateway:
    build: ./BACKEND/Gateway
    container_name: gateway
    ports:
      - "3000:3000"
    depends_on:
      - userservice
      - authservice
    networks:
      - webnet
  
  userservice:
    build: ./BACKEND/User
    container_name: userservice
    ports:
      - "3001:3001"
    env_file:
      - ./BACKEND/User/.env
    networks:
      - webnet
  
  authservice:
    build: ./BACKEND/Authentication
    container_name: authservice
    ports:
      - "3002:3002"
    env_file:
      - ./BACKEND/Authentication/.env
    networks:
      - webnet

  chatservice:
    build: ./BACKEND/Chat
    container_name: chatservice
    ports:
      - "3004:3004"
    networks:
      - webnet

  onlinepongservice:
    build: ./BACKEND/OnlinePong
    container_name: onlinepongservice
    ports:
      - "3005:3005"
    networks:
      - webnet

  friendservice:
    build: ./BACKEND/Friend
    container_name: friendservice
    ports:
      - "3006:3006"
    env_file:
      - ./BACKEND/Friend/.env
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  vault-data:
    driver: local