ALTER TABLE user_stats ADD COLUMN returned INTEGER DEFAULT 0;
ALTER TABLE user_stats ADD COLUMN streak INTEGER DEFAULT 0;
ALTER TABLE user_stats ADD COLUMN max_streak INTEGER DEFAULT 0;
ALTER TABLE user_stats ADD COLUMN maxCombo INTEGER DEFAULT 0;