SecRuleEngine On

SecAuditEngine RelevantOnly
SecAuditLog /var/log/modsec_audit.log

# Include OWASP Core Rule Set (CRS)
Include /usr/local/modsecurity-crs/crs-setup.conf
Include /usr/local/modsecurity-crs/rules/*.conf
