
server{
    listen 8080;
    server_name _;
    return 301 https://$host:9443$request_uri; #redirection de toute http vers https
}

server{
    listen 9443 ssl default_server; 
    server_name _;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate /etc/ssl/certs/nginx.crt;
    ssl_certificate_key /etc/ssl/certs/nginx.key;
    ssl_stapling        off;
    ssl_stapling_verify off;

    root /usr/share/nginx/html/;
    index index.html index.htm ;

    #header de securite pour proteger contre les attaques XSS, Clickjacking, etc.
    add_header X-Content-Type-Options nosniff; #empecher le nav de deviner le type de fichier envoyer par le serveur
    add_header X-Frame-Options DENY; #Empêcher que la page soit intégrée dans un <iframe> d’un autre site (clickjacking)
    add_header X-XSS-Protection "1; mode=block"; #Activer la protection XSS intégrée à certains navigateurs
    add_header Referrer-Policy no-referrer; #Contrôler quelles informations de référence (Referrer) sont envoyées aux autres sites
    add_header Permissions-Policy "geolocation=(), microphone=()"; #Limiter les fonctionnalités du navigateur accessibles depuis votre site

    
    location / {
        proxy_pass http://web:8080; #redirection vers le service frontend
        proxy_set_header Host $host; #ne modifie pas le host de l'utilisateur
        proxy_set_header X-Real-IP $remote_addr; #garde l'addresse IP de l'utilisateur pour que la requete vers le back ne semble pas venir de l'iginx
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header cookie $http_cookie;
    }

    # location / {
    #     try_files $uri $uri/ /index.html;
    # }
    
    location /auth/ {
        proxy_pass http://gateway:3000; #redirection vers le service backend
        proxy_set_header Host $host; #ne modifie pas le host de l'utilisateur
        proxy_set_header X-Real-IP $remote_addr; #garde l'addresse IP de l'utilisateur pour que la requete vers le back ne semble pas venir de l'iginx
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header cookie $http_cookie;
    }

    # location ~ /\.(?!well-known).* { #protege les fichier cacher et sensible dans le root si jamais
    #     deny all;
    # }
}