user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events{
    worker_connexion 1024;
}

http{
    server_tokens off; #dit a nginx de ne pas afficher sa version sur l'entete de la page d'erreur
    include /etc/nginx/mime.types;
	default_type application/octet-stream;

    server{
        listen 8080;
        root /usr/share/nginx/html/;
        index index.html index.htm ;

        #header de securite pour proteger contre les attaques XSS, Clickjacking, etc.
        add_header X-Content-Type-Options nosniff; #empecher le nav de deviner le type de fichier envoyer par le serveur 
        add_header X-Frame-Options DENY; #Empêcher que la page soit intégrée dans un <iframe> d’un autre site (clickjacking)
        add_header X-XSS-Protection "1; mode=block"; #Activer la protection XSS intégrée à certains navigateurs
        add_header Referrer-Policy no-referrer; #Contrôler quelles informations de référence (Referrer) sont envoyées aux autres sites
        add_header Permissions-Policy "geolocation=(), microphone=()"; #Limiter les fonctionnalités du navigateur accessibles depuis votre site

        location ~ /\.(?!well-known).* { #protege les fichier cacher et sensible dans le root si jamais
            deny all;
        }

        location / {
            try_files $uri $uri/ =404;
        }
        
        location /api/ {
            proxy_pass http://gateway_service:3000/; #redirection vers le service backend
            proxy_set_header Host $host; #ne modifie pas le host de l'utilisateur
            proxy_set_header X-Real-IP $remote_addr; #garde l'addresse IP de l'utilisateur pour que la requete vers le back ne semble pas venir de l'iginx
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}